version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:8000 --workers 1 server.wsgi
    environment:
      FRONTEND_URL: ${FRONTEND_URL}
      BACKEND_URL: ${BACKEND_URL}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GITLAB_CLIENT_ID: ${GITLAB_CLIENT_ID}
      GITLAB_CLIENT_SECRET: ${GITLAB_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      CORS_ALLOWED_ORIGINS: ${FRONTEND_URL}
      REPOS_FOLDER: /repos
      PRODUCTION: "1"
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - $REPOS_HOST_FOLDER:/repos
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        APP_API_URL: ${BACKEND_URL}
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend
